### ISSUE TITLE
Cannot set Ask ChatGPT as default

### ISSUE THREAD

**Issue by mifitous** [giaphiep/chatgpt-wizard#1]
It constantly switch back to Grammar correction
Google Chrome	123.0.6312.107 (Official Build) (arm64) 
Revision	399174dbe6eff0f59de9a6096129c0c827002b3a-refs/branch-heads/6312@{#761}
OS	macOS Version 14.4.1 (Build 23E224)

**Comment by giaphiep** [comment]
![Screenshot 2024-04-08 at 14 24 06](https://github.com/giaphiep/chatgpt-wizard/assets/7961675/e34bd5a8-ee35-414f-ab37-3cccb1d79248)
Yes. You're correct. I missing the code. I will update it. Thank you !!

**Comment by mifitous** [comment]
Fixed in https://github.com/giaphiep/chatgpt-wizard/commit/4d045ce852062e4e1d5e221b06ffb0012db7c821
